### PR TITLE
Add error dialog type and Windows and Mac icons

### PR DESCRIPTION
**Pull request by BoatsAreRockable**
This PR:
* Adds icons to Windows dialogues and add to those for Mac.
* Adds a new dialog type `error`.

I appreciate this project hasn't been active for a long time, but I can see it being potentially very handy for some NW.js work I have been doing.

### CODE REVIEW

**Comment by tomas** [comment]
Looks good, thanks. What version(s) of Windows did you try this on? Would you post a few screenshots to see how it looks like?

**Comment by BoatsAreRockable** [comment]
Hi @tomas, I've tested this in Windows 10. I'll get some screenshots for you later today.

**Comment by BoatsAreRockable** [comment]
Here are some screenshots on Windows 10:

error info warn

**Comment by tomas** [comment]
Looks good, thanks!

**Pull request merged**
